import Link from 'next/link';
import { MapPin, Bot, Heart } from 'lucide-react';
import {
  Button,
  Card,
  CardContent,
  CardTitle,
  CardDescription,
  Chip,
} from '@OmarZambranoDev/portfolio-ui';
import { featuredDestinations } from '@/data/destinations';

const FEATURES = [
  {
    icon: MapPin,
    title: 'Explore Destinations',
    description:
      'Browse curated destinations across every continent, filtered by region, category, and travel style.',
  },
  {
    icon: Bot,
    title: 'AI Trip Planner',
    description:
      'Describe your dream trip and get a personalized itinerary generated by AI in seconds.',
  },
  {
    icon: Heart,
    title: 'Save Your Trips',
    description:
      'Save destinations and planned itineraries to revisit and refine whenever you are ready.',
  },
];

export default function HomePage() {
  return (
    <div className="flex flex-col gap-16">
      {/* Hero */}
      <section className="flex flex-col items-center text-center gap-6 py-16">
        <Chip variant="accent" size="sm">
          AI-Powered Travel Planning
        </Chip>
        <h1 className="text-4xl md:text-6xl font-bold text-earth-forest max-w-3xl leading-tight">
          Your next adventure starts here
        </h1>
        <p className="text-lg text-secondary max-w-xl">
          Discover breathtaking destinations, plan personalized itineraries with AI, and save your
          dream trips — all in one place.
        </p>
        <div className="flex items-center gap-3 flex-wrap justify-center">
          <Link href="/destinations">
            <Button variant="primary" size="lg">
              <MapPin className="w-4 h-4" />
              Explore Destinations
            </Button>
          </Link>
          <Link href="/plan">
            <Button variant="outline" size="lg">
              <Bot className="w-4 h-4" />
              Plan with AI
            </Button>
          </Link>
        </div>
      </section>

      {/* Features */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {FEATURES.map(({ icon: Icon, title, description }) => (
          <Card key={title} variant="elevated">
            <CardContent className="flex flex-col gap-3 p-6">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <Icon className="w-5 h-5 text-primary" />
              </div>
              <CardTitle>{title}</CardTitle>
              <CardDescription>{description}</CardDescription>
            </CardContent>
          </Card>
        ))}
      </section>

      {/* Featured Destinations */}
      <section className="flex flex-col gap-6">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold text-earth-forest">Featured Destinations</h2>
          <Link href="/destinations">
            <Button variant="outline" size="sm">
              View all
            </Button>
          </Link>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {featuredDestinations.map((destination) => (
            <Link key={destination.slug} href={`/destinations/${destination.slug}`}>
              <Card variant="elevated" clickable>
                <CardContent className="flex flex-col gap-2 p-6">
                  <div className="flex items-center gap-2 flex-wrap">
                    {destination.categories.map((cat) => (
                      <Chip key={cat} variant="default" size="sm">
                        {cat}
                      </Chip>
                    ))}
                  </div>
                  <CardTitle>{destination.name}</CardTitle>
                  <CardDescription>{destination.country}</CardDescription>
                  <p className="text-sm text-secondary mt-1">{destination.tagline}</p>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
